// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIpJ4JyHbsdK0L7lNYfHA4g0GL78CRgAg',
    appId: '1:50875708573:web:3e837c31137ee9a673d074',
    messagingSenderId: '50875708573',
    projectId: 'fast-sign-455517-b7',
    authDomain: 'fast-sign-455517-b7.firebaseapp.com',
    storageBucket: 'fast-sign-455517-b7.firebasestorage.app',
    measurementId: 'G-ESJ1M0KYCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj7ar0qIIJ2U6SP7ewTPxvnx_lDyjfyjo',
    appId: '1:50875708573:android:19f621480d8fc5c173d074',
    messagingSenderId: '50875708573',
    projectId: 'fast-sign-455517-b7',
    storageBucket: 'fast-sign-455517-b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzBLt2vjq6QCrXL6OKQgyPwBmhU_Wphkk',
    appId: '1:50875708573:ios:efaa5a14a1b97ce073d074',
    messagingSenderId: '50875708573',
    projectId: 'fast-sign-455517-b7',
    storageBucket: 'fast-sign-455517-b7.firebasestorage.app',
    iosBundleId: 'com.example.backendtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzBLt2vjq6QCrXL6OKQgyPwBmhU_Wphkk',
    appId: '1:50875708573:ios:efaa5a14a1b97ce073d074',
    messagingSenderId: '50875708573',
    projectId: 'fast-sign-455517-b7',
    storageBucket: 'fast-sign-455517-b7.firebasestorage.app',
    iosBundleId: 'com.example.backendtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIpJ4JyHbsdK0L7lNYfHA4g0GL78CRgAg',
    appId: '1:50875708573:web:88af19a6fd3c53e773d074',
    messagingSenderId: '50875708573',
    projectId: 'fast-sign-455517-b7',
    authDomain: 'fast-sign-455517-b7.firebaseapp.com',
    storageBucket: 'fast-sign-455517-b7.firebasestorage.app',
    measurementId: 'G-N1QYP0JXLF',
  );

}